"use client";

import { useMemo, useState } from "react";
import {
  BadgeDollarSign, Banknote, Beef, Beer, BookOpen, Bot, Building2, Check, ChefHat,
  ChevronRight, CircleHelp, Citrus, Clock3, Crown, CupSoda, GraduationCap, Hammer,
  Info, Mailbox, MapPin, Megaphone, PackageOpen, Pizza, Plane, Play, Radio,
  RefreshCw, Store, Truck, UserMinus, Users, X,
} from "lucide-react";
import {
  DRINKS, EMPLOYEES, ENTRY_EMPLOYEES, PHASE_COPY, addGarden,
  addHouse, advance, capacity, cloneGame, expandRestaurant, fireEmployee, hire,
  initialGame, isValidRestaurantSpot, market, moveStartingRestaurant, openSlots, placeStartingRestaurant,
  price, procureFromSource, produce, reachableSources, roadDistance, toggleActive,
  train, validRestaurantPlacements, type CampaignType, type Employee, type GameState,
  type Good,
} from "./game";

const goodMeta: Record<Good, { label: string; icon: typeof Beef; color: string }> = {
  burger: { label: "Burger", icon: Beef, color: "#c64b35" },
  pizza: { label: "Pizza", icon: Pizza, color: "#d68b1d" },
  soda: { label: "Soft drink", icon: CupSoda, color: "#d94738" },
  lemonade: { label: "Lemonade", icon: Citrus, color: "#d0a91d" },
  beer: { label: "Beer", icon: Beer, color: "#397754" },
};

const campaignMeta: Record<CampaignType, { label: string; icon: typeof Megaphone }> = {
  billboard: { label: "Billboard", icon: Megaphone },
  mailbox: { label: "Mailbox", icon: Mailbox },
  airplane: { label: "Airplane", icon: Plane },
  radio: { label: "Radio", icon: Radio },
};

function EmployeeCard({ employee, active, selected, compact, supply, onClick }: { employee: Employee; active?: boolean; selected?: boolean; compact?: boolean; supply?: number; onClick?: () => void }) {
  const Icon = employee.track === "kitchen" ? ChefHat : employee.track === "marketing" ? Megaphone : employee.track === "training" ? GraduationCap : employee.track === "management" ? Users : employee.track === "pricing" ? BadgeDollarSign : employee.track === "buyer" ? Truck : employee.track === "expansion" ? Hammer : employee.track === "finance" ? Banknote : employee.track === "recruiting" ? Users : Store;
  return <button className={`employee-card ${active ? "is-active" : ""} ${selected ? "is-selected" : ""} ${compact ? "is-compact" : ""}`} onClick={onClick} disabled={!onClick} title={employee.description}>
    <span className="employee-icon"><Icon size={16} /></span>
    <span className="employee-copy"><strong>{employee.name}</strong><small>{employee.description}</small></span>
    <span className="employee-flags">{employee.salary && <b title="Salary: $5">$5</b>}{employee.slots && <b title={`${employee.slots} management slots`}>+{employee.slots}</b>}{supply !== undefined && <b title="Cards left">×{supply}</b>}</span>
    {active && <span className="working-dot" title="At work"><Check size={12} /></span>}
  </button>;
}

function GoodPill({ good, count }: { good: Good; count?: number }) {
  const { icon: Icon, label, color } = goodMeta[good];
  return <span className="good-pill" style={{ "--good": color } as React.CSSProperties}><Icon size={13} />{count === undefined ? label : count}</span>;
}

function Board({ game, mutate }: { game: GameState; mutate: (fn: (next: GameState) => void) => void }) {
  const canMoveStart = game.phase === "restructure" && game.round === 1 && game.players[0].restaurants.length === 1;
  const validSetup = useMemo(() => new Set(validRestaurantPlacements(game, true, canMoveStart ? { playerId: 0, restaurantId: game.players[0].restaurants[0].id } : undefined).map((spot) => `${spot.row},${spot.col}`)), [game, canMoveStart]);
  return <section className="board-wrap" aria-label="Modular city map">
    <div className="tile-key"><span>BASE MAP · 16 OF 20 TILES</span><span>Each outlined square is one 5×5 map tile</span></div>
    <div className="fcm-board">
      {game.board.cells.flat().map((cell) => <div key={`${cell.row}-${cell.col}`} className={`map-cell ${cell.kind === "road" ? "map-road" : "map-terrain"} ${cell.row % 5 === 0 ? "tile-top" : ""} ${cell.col % 5 === 0 ? "tile-left" : ""}`} style={{ gridRow: cell.row + 1, gridColumn: cell.col + 1 }} />)}
      {game.board.tiles.map((tile) => <span key={`${tile.row}-${tile.col}`} className="tile-letter" style={{ gridRow: tile.row * 5 + 1, gridColumn: tile.col * 5 + 1 }}>{tile.id}</span>)}
      {game.houses.map((house) => <button key={house.id} className={`map-house ${house.garden ? "has-garden" : ""} ${game.selectedHouse === house.id ? "selected" : ""}`} style={{ gridRow: `${house.row + 1} / span 2`, gridColumn: `${house.col + 1} / span 2` }} onClick={() => mutate((next) => { next.selectedHouse = next.selectedHouse === house.id ? null : house.id; next.selectedLot = null; })} aria-label={`House ${house.id}: ${house.demand.join(", ") || "no demand"}`}>
        <span className="house-number">{house.id}</span><Building2 size={18} />{house.garden && <span className="garden">garden</span>}
        <span className="demand-row">{house.demand.map((good, index) => { const Icon = goodMeta[good].icon; return <i key={`${good}-${index}`} style={{ background: goodMeta[good].color }}><Icon size={8} /></i>; })}</span>
      </button>)}
      {game.sources.map((source) => { const Icon = goodMeta[source.good].icon; return <button key={source.id} className="drink-source" style={{ gridRow: source.row + 1, gridColumn: source.col + 1, "--source": goodMeta[source.good].color } as React.CSSProperties} title={`${goodMeta[source.good].label} source`} onClick={() => mutate((next) => { next.selectedLot = { row: source.row, col: source.col }; next.selectedHouse = null; })}><Icon size={13} /></button>; })}
      {game.players.flatMap((player) => player.restaurants.map((restaurant) => <div key={`${player.id}-${restaurant.id}`} className={`map-restaurant ${restaurant.open ? "" : "coming-soon"}`} style={{ gridRow: `${restaurant.row + 1} / span 2`, gridColumn: `${restaurant.col + 1} / span 2`, "--chain": player.color } as React.CSSProperties} title={`${player.chain} restaurant${restaurant.open ? "" : " (coming soon)"}`}><Store size={15} /><span>{player.id === 0 ? "YOU" : player.chain.split(" ")[0]}</span><i style={{ gridRow: restaurant.entranceRow + 1, gridColumn: restaurant.entranceCol + 1 }} /></div>))}
      {game.campaigns.map((campaign) => { const house = game.houses.find((item) => item.id === campaign.targetHouseId); if (!house) return null; const Icon = campaignMeta[campaign.type].icon; return <div key={campaign.id} className="map-campaign" style={{ gridRow: house.row + 1, gridColumn: house.col + 2, background: game.players[campaign.playerId].color }} title={`${campaignMeta[campaign.type].label}: ${goodMeta[campaign.good].label}`}><Icon size={10} /></div>; })}
      {game.board.cells.flat().filter((cell) => cell.kind === "lot").map((cell) => {
        const key = `${cell.row},${cell.col}`; const setupSpot = (game.phase === "setup" || canMoveStart) && validSetup.has(key); const selected = game.selectedLot?.row === cell.row && game.selectedLot?.col === cell.col;
        const placementLabel = canMoveStart ? "Move restaurant" : "Place restaurant";
        return <button key={`lot-${key}`} className={`map-lot-button ${setupSpot ? "valid-restaurant" : ""} ${selected ? "selected" : ""}`} style={{ gridRow: cell.row + 1, gridColumn: cell.col + 1 }} onClick={() => setupSpot ? mutate((next) => canMoveStart ? moveStartingRestaurant(next, cell.row, cell.col) : placeStartingRestaurant(next, cell.row, cell.col)) : mutate((next) => { next.selectedLot = selected ? null : { row: cell.row, col: cell.col }; next.selectedHouse = null; })} aria-label={setupSpot ? `${placementLabel} starting at row ${cell.row + 1}, column ${cell.col + 1}` : `Empty lot row ${cell.row + 1}, column ${cell.col + 1}`} />;
      })}
    </div>
    <div className="board-legend"><span><i className="road-swatch" />Road</span><span><Building2 size={13} />House</span><span><Store size={13} />Restaurant</span>{DRINKS.map((good) => <GoodPill key={good} good={good} />)}<span className="legend-tip">Distance counts tile borders crossed along connected roads.</span></div>
  </section>;
}

function PlayerStrip({ game }: { game: GameState }) {
  return <div className="player-strip">{game.turnOrder.map((id, index) => { const player = game.players[id]; return <div key={id} className={`player-chip ${id === 0 ? "you" : ""}`} style={{ "--chain": player.color } as React.CSSProperties}><span className="order-number">{index + 1}</span><span className="chain-mark"><Store size={15} /></span><span><strong>{player.chain}</strong><small>{id === 0 ? "You" : `Bot · ${player.name}`}</small></span><b>${player.cash}</b><span className="stock-mini">{(Object.keys(goodMeta) as Good[]).map((good) => <GoodPill key={good} good={good} count={player.stock[good]} />)}</span></div>; })}</div>;
}

function PhaseRail({ game, mutate, openRules }: { game: GameState; mutate: (fn: (next: GameState) => void) => void; openRules: () => void }) {
  const phase = PHASE_COPY[game.phase]; const player = game.players[0]; const winner = [...game.players].sort((a, b) => b.cash - a.cash)[0];
  return <aside className="phase-rail">
    <div className="rail-head"><span className="phase-kicker">ROUND {game.round} · {phase.label}</span><h2>{phase.title}</h2><p>{phase.body}</p></div>
    {game.phase === "gameover" ? <div className="winner-panel"><Crown size={28} /><strong>{winner.chain} wins</strong><span>${winner.cash} cash</span></div> : game.phase !== "setup" && <div className="next-up"><Clock3 size={16} /><span><small>NOW</small>{game.phase === "work" ? "Your available actions are below" : "Review the board, then continue"}</span></div>}
    {game.selectedHouse && (() => { const house = game.houses.find((item) => item.id === game.selectedHouse)!; return <div className="house-inspector"><div><Building2 size={16} /><strong>House {house.id}</strong>{house.garden && <span>Garden</span>}</div><p>{house.demand.length ? `Wants ${house.demand.join(" + ")}. A chain must have every item.` : "No demand yet. Marketing can create it."}</p><div className="distance-list">{game.players.map((item) => { const distance = roadDistance(game, item, house); return <span key={item.id}><i style={{ background: item.color }} />{item.chain}<b>{distance === Infinity ? "—" : distance}</b></span>; })}</div></div>; })()}
    {game.selectedLot && <div className="lot-inspector"><MapPin size={15} /><span><strong>Map square</strong>Row {game.selectedLot.row + 1}, column {game.selectedLot.col + 1}</span></div>}
    <div className="rule-note"><Info size={16} /><p><strong>Why this matters</strong>{game.phase === "setup" ? "Your entrance must touch a road, and no starting restaurant may share an entrance tile with another chain." : game.phase === "restructure" && game.round === 1 ? `Your restaurant is still provisional. Click another highlighted 2×2 area to move it; Lock company makes its position final. You have ${capacity(player, game.ceoSlots)} company slots.` : game.phase === "restructure" ? `You have ${capacity(player, game.ceoSlots)} total slots. Managers must report directly to your ${game.ceoSlots}-slot CEO.` : game.phase === "work" ? `Your current unit price is $${price(player)}. The CEO hire action is always available.` : game.phase === "dinner" ? "Customers compare unit price plus road distance measured in tile borders, not map squares." : game.phase === "marketing" ? "Demand appears after dinner, so advertising prepares customers for a later round." : "The event log records every rule-driven change."}</p></div>
    {game.phase !== "setup" && <button className="primary-action" data-testid="advance-phase" onClick={() => mutate((next) => game.phase === "gameover" ? Object.assign(next, initialGame(next.players[0].reserve, next.players[0].reserveSlots, true), { gameStarted: true }) : advance(next))}>{game.phase === "gameover" ? <RefreshCw size={17} /> : <Play size={17} />}{phase.action}<ChevronRight size={16} /></button>}
    <button className="text-action" onClick={openRules}><BookOpen size={15} /> Open rules reference</button>
    <div className="event-log"><div className="section-label"><span>Event log</span><span>Latest first</span></div>{game.log.slice(0, 9).map((event) => <div key={event.id} className={`event ${event.tone ?? ""}`}><i /><span>{event.text}</span><small>R{event.round}</small></div>)}</div>
  </aside>;
}

type WorkTab = "company" | "hire" | "train" | "produce" | "market" | "expand";

function Workbench({ game, mutate }: { game: GameState; mutate: (fn: (next: GameState) => void) => void }) {
  const player = game.players[0]; const [tab, setTab] = useState<WorkTab>(() => game.phase === "work" ? "hire" : "company"); const [marketGood, setMarketGood] = useState<Good>("burger"); const [marketer, setMarketer] = useState<number | null>(null); const [campaignType, setCampaignType] = useState<CampaignType>("billboard");
  const busy = new Set(game.campaigns.filter((campaign) => campaign.playerId === 0).map((campaign) => campaign.marketeerIndex));
  const beach = player.roster.map((id, index) => ({ id, index })).filter((item) => !player.active.includes(item.index) && !busy.has(item.index)); const phaseWork = game.phase === "work";
  const tabs = [["company", "Company", Users], ["hire", `Hire · ${Math.max(0, game.work.hires)}`, Users], ["train", `Train · ${game.work.training}`, GraduationCap], ["market", `Market · ${game.work.marketed.length}`, Megaphone], ["produce", `Food & drinks · ${game.work.produced.length}`, PackageOpen], ["expand", `Map · ${game.work.builders.length + game.work.restaurantManagers.length}`, Hammer]] as const;
  const selectedMarketer = marketer === null ? null : EMPLOYEES[player.roster[marketer]];
  return <section className="workbench">
    <div className="workbench-top"><div><span className="section-label">YOUR COMPANY</span><h2>{player.chain}</h2></div><div className="company-stats"><span><Banknote size={15} />Cash <b>${player.cash}</b></span><span>Price <b>${price(player)}</b></span><span>Slots <b>{player.active.length}/{capacity(player, game.ceoSlots)}</b></span><span className="inventory">{(Object.keys(goodMeta) as Good[]).map((good) => <GoodPill key={good} good={good} count={player.stock[good]} />)}</span></div></div>
    <div className="tabs" role="tablist">{tabs.map(([id, label, Icon]) => <button key={id} role="tab" aria-selected={tab === id} onClick={() => setTab(id)} disabled={id !== "company" && !phaseWork}><Icon size={15} />{label}</button>)}</div>
    <div className="workbench-body">
      {tab === "company" && <><div className="org-chart"><div className="ceo-card"><Crown size={18} /><span><strong>CEO</strong><small>Always works · hires 1</small></span><b>{game.ceoSlots} direct slots</b></div><div className="employee-grid">{player.roster.length ? player.roster.map((id, index) => <div key={`${id}-${index}`} className="employee-stack"><EmployeeCard employee={EMPLOYEES[id]} active={player.active.includes(index)} onClick={game.phase === "restructure" && !busy.has(index) ? () => mutate((next) => toggleActive(next, index)) : undefined} />{busy.has(index) && <span className="busy-label">Busy marketing</span>}{game.phase === "payday" && !busy.has(index) && <button className="fire-button" onClick={() => mutate((next) => fireEmployee(next, index))}><UserMinus size={12} />Fire</button>}</div>) : <div className="empty-company"><Users size={24} /><strong>Your CEO is flying solo.</strong><span>Place your restaurant, lock the company, then use the guaranteed CEO hire.</span></div>}</div></div><div className="tab-help"><CircleHelp size={15} /><span>{game.phase === "restructure" ? `Click employees to put them to work. ${openSlots(player, game.ceoSlots)} slots remain open.` : game.phase === "payday" ? "You may fire employees before paying. Salary icons cost $5 even on the beach." : "Highlighted cards work this round; marketing staff marked busy are unavailable."}</span></div></>}
      {tab === "hire" && <><div className="action-banner"><Users size={17} /><span><strong>{game.work.hires > 0 ? `You can hire ${game.work.hires} employee${game.work.hires === 1 ? "" : "s"}` : "Recruiting complete"}</strong>Your CEO always supplies the first hire. Click any available entry card.</span></div><div className="employee-grid market-grid">{ENTRY_EMPLOYEES.map((employee) => <EmployeeCard key={employee.id} employee={employee} supply={game.supply[employee.id]} onClick={game.work.hires > 0 && game.supply[employee.id] > 0 ? () => mutate((next) => hire(next, employee.id)) : undefined} />)}</div><div className="tab-help"><CircleHelp size={15} /><span>New hires go to the beach. They may be trained this turn, but cannot work until next round.</span></div></>}
      {tab === "train" && <><div className="employee-grid">{beach.filter(({ id }) => EMPLOYEES[id].next?.length).map(({ id, index }) => <div key={index} className="training-row"><EmployeeCard employee={EMPLOYEES[id]} compact /><ChevronRight size={15} />{EMPLOYEES[id].next!.map((nextId) => <button key={nextId} onClick={() => mutate((next) => train(next, index, nextId))} disabled={!game.work.training || game.supply[nextId] <= 0}><GraduationCap size={14} />{EMPLOYEES[nextId].name}<small>×{game.supply[nextId]}</small></button>)}</div>)}{!beach.some(({ id }) => EMPLOYEES[id].next?.length) && <div className="empty-company"><GraduationCap size={24} /><strong>No trainable beach employee.</strong><span>The career arrows now match the employee display in the rulebook.</span></div>}</div><div className="tab-help"><CircleHelp size={15} /><span>Only beach employees may train. Card supply is finite.</span></div></>}
      {tab === "produce" && <><div className="production-list">{game.work.produced.map((index) => { const employee = EMPLOYEES[player.roster[index]]; const sources = reachableSources(game, player, employee); return <div key={index} className="production-action"><EmployeeCard employee={employee} compact />{employee.produces && (Object.keys(employee.produces) as Good[]).map((good) => <button key={good} onClick={() => mutate((next) => produce(next, index, good))}><GoodPill good={good} />Get {employee.produces![good]}</button>)}{employee.buyer?.anyDrink && DRINKS.map((good) => <button key={good} onClick={() => mutate((next) => produce(next, index, good))}><GoodPill good={good} />Choose</button>)}{employee.buyer && !employee.buyer.anyDrink && sources.map((source) => <button key={source.id} onClick={() => mutate((next) => procureFromSource(next, index, source.id))}><GoodPill good={source.good} />Source {source.id}</button>)}{employee.buyer && !employee.buyer.anyDrink && !sources.length && <small className="no-route">No source is reachable from an open restaurant.</small>}</div>; })}{!game.work.produced.length && <div className="empty-company"><ChefHat size={24} /><strong>No unused food or drink actions.</strong><span>Kitchen staff produce food. Cart, truck, and zeppelin routes use the drink sources printed on the map.</span></div>}</div><div className="tab-help"><CircleHelp size={15} /><span>Cart and truck ranges count tile borders along roads. Zeppelins count tiles and ignore roads.</span></div></>}
      {tab === "market" && <><div className="market-controls"><span>1. Choose a marketeer</span><div>{game.work.marketed.map((index) => <button key={index} className={marketer === index ? "selected" : ""} onClick={() => { setMarketer(index); setCampaignType(EMPLOYEES[player.roster[index]].campaigns![0]); }}>{EMPLOYEES[player.roster[index]].name}</button>)}</div><span>2. Choose campaign</span><div>{selectedMarketer?.campaigns?.map((type) => { const Icon = campaignMeta[type].icon; return <button key={type} className={campaignType === type ? "selected" : ""} onClick={() => setCampaignType(type)}><Icon size={14} />{campaignMeta[type].label}</button>; })}</div><span>3. Choose a product</span><div>{(Object.keys(goodMeta) as Good[]).map((good) => <button key={good} className={marketGood === good ? "selected" : ""} onClick={() => setMarketGood(good)}><GoodPill good={good} /></button>)}</div><span>4. Select a house on the map</span><button className="launch-button" disabled={marketer === null || game.selectedHouse === null} onClick={() => { if (marketer !== null && game.selectedHouse !== null) { mutate((next) => market(next, marketer, game.selectedHouse!, marketGood, campaignType)); setMarketer(null); } }}><Megaphone size={16} />Launch {campaignMeta[campaignType].label.toLowerCase()} near house {game.selectedHouse ?? "—"}</button></div><div className="tab-help"><CircleHelp size={15} /><span>Marketeers become busy until their campaign ends. Campaign type controls which houses receive demand.</span></div></>}
      {tab === "expand" && <><div className="action-banner"><MapPin size={17} /><span><strong>Select a house or empty lot on the map</strong>New Business Developers add houses/gardens; Local and Regional Managers place restaurants.</span></div><div className="expansion-actions">{game.work.builders.map((index) => <div key={`builder-${index}`}><EmployeeCard employee={EMPLOYEES[player.roster[index]]} compact /><button disabled={!game.selectedHouse || game.houses.find((house) => house.id === game.selectedHouse)?.garden} onClick={() => mutate((next) => addGarden(next, index, next.selectedHouse!))}>Add garden</button><button disabled={!game.selectedLot} onClick={() => mutate((next) => addHouse(next, index, next.selectedLot!.row, next.selectedLot!.col))}>Place garden house</button></div>)}{game.work.restaurantManagers.map((index) => <div key={`manager-${index}`}><EmployeeCard employee={EMPLOYEES[player.roster[index]]} compact /><button disabled={!game.selectedLot || !isValidRestaurantSpot(game, game.selectedLot.row, game.selectedLot.col)} onClick={() => mutate((next) => expandRestaurant(next, index, next.selectedLot!.row, next.selectedLot!.col))}>Place restaurant</button></div>)}{!game.work.builders.length && !game.work.restaurantManagers.length && <div className="empty-company"><Hammer size={24} /><strong>No map-development actions.</strong><span>Train the Waitress path into New Business Developer or Local Manager.</span></div>}</div></>}
    </div>
  </section>;
}

function StartDialog({ onStart }: { onStart: (reserve: number, slots: number) => void }) {
  const [reserve, setReserve] = useState(200);
  const [slots, setSlots] = useState(3);
  return <div className="modal-backdrop"><div className="start-dialog"><div className="start-brand"><span className="brand-mark"><Store /></span><div><span>A guided base-game adaptation</span><h1>Food Chain<br />Magnate</h1></div></div><p className="start-lede">Build a restaurant empire across the real twenty-tile city system and play the complete seven-phase economy against three bot executives.</p><div className="opponent-row"><span><Bot />Mara<small>Sales-focused</small></span><span><Bot />Otto<small>Pizza specialist</small></span><span><Bot />June<small>Marketing-first</small></span></div><fieldset><legend>Choose your hidden bank reserve card</legend><p>Choose its dollar value and CEO-slot icon separately. Both remain hidden until the bank first breaks.</p><div className="reserve-options">{[100, 200, 300].map((amount) => <button key={amount} className={reserve === amount ? "selected" : ""} onClick={() => setReserve(amount)}><Banknote />${amount}{reserve === amount && <Check />}</button>)}</div><div className="slot-options" aria-label="CEO slots">{[2, 3, 4].map((count) => <button key={count} className={slots === count ? "selected" : ""} onClick={() => setSlots(count)}><Users size={15} />{count} CEO slots{slots === count && <Check size={14} />}</button>)}</div></fieldset><button className="start-button" onClick={() => onStart(reserve, slots)}><Play />Build the city</button><small className="adaptation-note">Base game · 4 players · Guided local state</small></div></div>;
}

function RulesDrawer({ onClose }: { onClose: () => void }) {
  return <div className="drawer-backdrop" onClick={onClose}><aside className="rules-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><span className="section-label">QUICK REFERENCE</span><h2>How the game flows</h2></div><button onClick={onClose} aria-label="Close rules"><X /></button></div>{Object.entries(PHASE_COPY).filter(([id]) => id !== "gameover").map(([id, copy]) => <div className="rule-phase" key={id}><span>{copy.label}</span><div><strong>{copy.title}</strong><p>{copy.body}</p></div></div>)}<div className="rule-callout"><Crown /><div><strong>How you win</strong><p>When the bank breaks once, hidden reserves extend the game and may change CEO slots. When it breaks a second time during dinner, the richest chain wins immediately.</p></div></div><a href="https://www.boardgamehelpers.com/FoodChainMagnate/Images/FCM_Rules_EN_v3.pdf" target="_blank" rel="noreferrer">Open the published base-game rulebook <ChevronRight /></a></aside></div>;
}

export default function Home() {
  const [game, setGame] = useState<GameState>(() => initialGame()); const [rulesOpen, setRulesOpen] = useState(false);
  const mutate = (fn: (next: GameState) => void) => setGame((current) => { const next = cloneGame(current); fn(next); return next; });
  const phase = PHASE_COPY[game.phase]; const bankPct = Math.max(0, Math.min(100, (game.bank / (game.bankBreaks ? 800 : 200)) * 100)); const milestones = game.players[0].milestones;
  return <main><header className="topbar"><div className="brand"><span className="brand-mark"><Store size={20} /></span><div><strong>FOOD CHAIN</strong><span>MAGNATE</span></div></div><div className="round-status"><span>Round <b>{game.round}</b></span><i /><span>{phase.title}</span></div><div className="bank-status"><span><Banknote size={16} />Bank</span><div><i style={{ width: `${bankPct}%` }} /></div><b>${Math.max(0, game.bank)}</b><small>{game.bankBreaks}/2 breaks</small></div><button className="icon-button" aria-label="Open rules" title="Rules" onClick={() => setRulesOpen(true)}><BookOpen size={18} /></button></header>
    <div className="game-shell"><div className="main-table"><PlayerStrip game={game} /><Board game={game} mutate={mutate} /><Workbench key={`${game.round}-${game.phase}`} game={game} mutate={mutate} />{milestones.length > 0 && <section className="milestones"><span className="section-label">YOUR MILESTONES</span>{milestones.map((milestone) => <span key={milestone}><Crown size={13} />{milestone}</span>)}</section>}</div><PhaseRail game={game} mutate={mutate} openRules={() => setRulesOpen(true)} /></div>
    {!game.gameStarted && <StartDialog onStart={(reserve, slots) => setGame({ ...initialGame(reserve, slots, true), gameStarted: true })} />}{rulesOpen && <RulesDrawer onClose={() => setRulesOpen(false)} />}</main>;
}
